In [1]:
import numpy as np
import pandas as pd
import sklearn
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import *
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
from sklearn import svm
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',5000000)
plt.figure(figsize=(14, 8))

RANDOM_SEED = 42
LABELS = ["Valid", "Fraud"]

In [ ]:

df1=pd.read_csv(r"train_transaction.csv")
df2=pd.read_csv(r"train_identity.csv")
training_data=pd.merge(df1,df2,how='left',on='TransactionID')  #all records from df1 and common records from df2
print("Training data",training_data.shape)

df3=pd.read_csv(r"test_transaction.csv")
df4=pd.read_csv(r"test_identity.csv")
testing_data=pd.merge(df3,df4,how='left',on='TransactionID')  #all records from df1 and common records from df2
print("Testing data",testing_data.shape)

Training data (590540, 434)

In [1]:
import pandas as pd
import pickle

# Load the pickle file containing the DataFrame
with open('train_Data.pkl', 'rb') as trf:
    train_Data = pickle.load(trf)

In [2]:
train_Data.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V_features_1,V_features_2,ID_1,ID_2,M_1,M_2,D_1,D_2,C_1,C_2
0,2987000.0,0.0,86400.0,68.5,4.0,13926.0,362.555488,150.0,1.0,142.0,...,-0.925114,-1.903989,-2.905561e-14,1.229590e-13,-6.797219e-01,9.403131e-01,-1.131826,0.193982,-0.331272,-0.334273
1,2987001.0,0.0,86401.0,29.0,4.0,2755.0,404.000000,150.0,2.0,102.0,...,-0.814293,-1.032186,-2.905561e-14,1.229590e-13,-1.864135e-01,9.334884e-01,-1.253859,0.250887,-0.338282,-0.370772
2,2987002.0,0.0,86469.0,59.0,4.0,4663.0,490.000000,150.0,3.0,166.0,...,-0.997526,-2.228729,-2.905561e-14,1.229590e-13,7.713390e-01,-1.345657e+00,-0.258904,-0.231988,-0.334589,-0.334193
3,2987003.0,0.0,86499.0,50.0,4.0,18132.0,567.000000,150.0,2.0,117.0,...,1.844165,-3.055586,-2.905561e-14,1.229590e-13,1.220769e-01,-9.190615e-01,-0.437551,-0.483755,-0.264718,-0.264662
4,2987004.0,0.0,86506.0,50.0,1.0,4497.0,514.000000,150.0,2.0,102.0,...,-0.626835,0.635191,1.110920e+00,2.691959e+00,-1.057116e-15,3.159337e-15,-0.295614,-0.121127,-0.331892,-0.373663

In [3]:
with open('test_Data.pkl', 'rb') as trf:
    test_Data = pickle.load(trf)

In [4]:
test_Data.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V_features_1,V_features_2,ID_1,ID_2,M_1,M_2,D_1,D_2,C_1,C_2
0,3663549.0,18403224.0,31.95,4.0,10409.0,111.0,150.0,3.0,226.0,2.0,...,-3.208410,-1.022232,-1.655473e-14,3.146013e-14,-0.028176,2.470650,2.253319,-0.379063,-0.003926,0.441541
1,3663550.0,18403263.0,49.00,4.0,4272.0,111.0,150.0,3.0,226.0,2.0,...,-2.879843,0.092682,-1.655473e-14,3.146013e-14,3.375785,1.515379,2.174106,-0.620442,-0.317695,-0.230457
2,3663551.0,18403310.0,171.00,4.0,4476.0,574.0,150.0,3.0,226.0,2.0,...,-2.840078,0.640378,-1.655473e-14,3.146013e-14,2.332404,-0.951521,-0.529100,-0.364418,-0.267695,-0.126762
3,3663552.0,18403310.0,284.95,4.0,10989.0,360.0,150.0,3.0,166.0,2.0,...,-4.447665,-0.008403,-1.655473e-14,3.146013e-14,-0.606868,0.093383,-0.010142,-0.004983,-0.294959,-0.209386
4,3663553.0,18403317.0,67.95,4.0,18018.0,452.0,150.0,2.0,117.0,2.0,...,-4.430801,0.761343,-1.655473e-14,3.146013e-14,-0.769832,-0.027809,-1.609382,-0.310529,-0.177815,-0.059605